// The notebook's own strings. UI_STRINGS in App.tsx is module-private and has
// no placeholder convention, and the sheet lives in its own component file;
// keeping both tables here, with `satisfies`, means a key missing from one
// language fails `tsc` rather than showing up as "undefined" in a hall.
//
// The feature is called Notizblock / Notebook. Never "Notizen" alone: that
// word already labels the per-coachee notes box on the Coachees tab, and two
// things called the same with different privacy on one screen is the
// confusion this name avoids.

export type PadLang = 'DE' | 'EN';

export const fill = (s: string, v: Record<string, string | number>): string =>
  s.replace(/\{(\w+)\}/g, (_, k: string) => String(v[k] ?? ''));

const DE = {
  padTitle: 'Notizblock',
  padLaunch: 'Notizblock öffnen',
  padPrivacy: 'Privat: nur du siehst diese Seiten. Jede Seite wird eine Woche nach dem Schreiben gelöscht. Nichts davon geht an den Schiedsrichter — ausser du tippst «Übernehmen».',
  padExpires: 'Wird am {date} gelöscht',
  padExpiresSoon: 'Wird morgen gelöscht',
  padCreated: 'Erstellt {date}',
  padEdited: 'Bearbeitet {time}',
  padTitlePlaceholder: 'Titel (optional)',
  padNewPage: 'Neue Seite',
  padNewText: 'Textseite',
  padNewInk: 'Stiftseite',
  padPageOf: 'Seite {n} von {m}',
  padPrevPage: 'Neuere Seite',
  padNextPage: 'Ältere Seite',
  padPagesFull: 'Höchstens 40 Seiten — lösche eine, um Platz zu machen.',
  padPlaceholder: 'Schreib hier …',
  padTime: 'Zeit',
  padTimeTitle: 'Uhrzeit einfügen',
  padSection: 'Abschnitt',
  padSectionTitle: 'Spielabschnitt einfügen',
  padSectionPre: 'Vorspiel',
  padSectionProtocol: 'Protokoll',
  padSectionSet: 'Satz {n}',
  padSectionBreak: 'Satzpause',
  padSectionPost: 'Nach dem Spiel',
  padEmpty: 'Noch keine Seiten. Schreib los — oder nimm den Stift.',
  padDeletePage: 'Seite löschen',
  padDeleteTitle: 'Seite löschen?',
  padDeleteMsg: 'Die Seite wird auf allen deinen Geräten gelöscht.',
  padSaving: 'Wird gespeichert…',
  padSaved: 'Gespeichert',
  padSynced: 'Auf dem Server gesichert',
  padSyncPending: 'Server folgt, sobald online',
  padSyncFailed: 'Server hat die Seite abgelehnt',
  padSyncRejected: 'Diese Seite wurde vom Server abgelehnt ({reason}) — bearbeite sie, um es erneut zu versuchen.',
  padNoStore: 'Dieses Gerät kann den Notizblock nicht speichern (privater Modus?).',
  padServerOnly: 'Nur auf dem Server gesichert — dieses Gerät speichert nichts.',
  padSaveFailed: 'Seite konnte nicht gespeichert werden — Speicher voll?',
  padInsert: 'Übernehmen…',
  padInsertTitle: 'Übernehmen',
  padInsertFor: 'Für: {role} · {name} (aktuelles Formular)',
  padInsertTarget: 'Ziel',
  padInsertRemarks: 'Bemerkungen',
  padInsertHighlights: 'Highlights & Potenziale',
  padInsertImprovements: 'Verbesserung',
  padInsertGoals: 'Ziele',
  padInsertTips: 'Tipps & Tricks (nur E-Mail)',
  padInsertCount1: '1 Seite → {field} ({role})',
  padInsertCountN: '{n} Seiten → {field} ({role})',
  padInsertNone: 'Keine Seite gewählt',
  padImportWarn: 'Übernommener Text wird Teil des Feedbacks und geht mit dem PDF per E-Mail an den Schiedsrichter.',
  padImportWarnTips: 'Tipps & Tricks gehen nur per E-Mail an den Schiedsrichter, nicht ins Feedback.',
  padInserted1: '1 Seite in «{field}» übernommen — geht mit dem Feedback an den Schiedsrichter.',
  padInsertedN: '{n} Seiten in «{field}» übernommen — geht mit dem Feedback an den Schiedsrichter.',
  padInsertAgainTitle: 'Nochmals übernehmen?',
  padInsertAgainMsg: 'Diese Seite wurde bereits in «{field}» übernommen.',
  padUsedIn: 'übernommen → {field} ({role}) · {label}',
  padShowUsed: 'Bereits übernommene anzeigen',
  padInkOnly: 'Stiftseite — kann nicht übernommen werden, nur angesehen.',
  padInkNotImported: 'Stiftseiten werden nicht übernommen — sie sind zum Nachlesen.',
  padReviewOnly: 'Beobachtung gesendet — der Notizblock bleibt privat; übernehmen geht hier nicht mehr.',
  padPenBlack: 'Stift',
  padPenRed: 'Rot',
  padEraser: 'Radierer',
  padUndo: 'Rückgängig',
  padClearPage: 'Seite leeren',
  padClearPageTitle: 'Seite leeren?',
  padClearPageMsg: 'Alle Striche auf dieser Seite werden gelöscht.',
  padFinger: 'Finger',
  padFingerOn: 'Finger zeichnet',
  padFingerOff: 'Nur der Stift zeichnet',
  padPenSeen: 'Stift erkannt — der Finger zeichnet jetzt nicht mehr.',
  padPageFull: 'Seite voll — bitte eine neue Seite beginnen.',
  padInkLoading: 'Stiftseite wird geladen…',
  padScribbleHint: 'Striche fehlen? Auf dem iPad: Einstellungen → Apple Pencil → Kritzeln aus.',
  padFull: 'Vollbild',
  padFullExit: 'Vollbild verlassen',
  padCourt: 'Spielfeld',
  padTextPageShort: 'Text',
  padInkPageShort: 'Stift',
  padCancel: 'Abbrechen',
  padClose: 'Schliessen',
  padBack: 'Zurück zu den Seiten',
} as const;

const EN: Record<keyof typeof DE, string> = {
  padTitle: 'Notebook',
  padLaunch: 'Open the notebook',
  padPrivacy: 'Private: only you can see these pages. Every page is deleted one week after it was written. Nothing here reaches the referee — unless you tap "Insert".',
  padExpires: 'Will be deleted on {date}',
  padExpiresSoon: 'Will be deleted tomorrow',
  padCreated: 'Written {date}',
  padEdited: 'Edited {time}',
  padTitlePlaceholder: 'Title (optional)',
  padNewPage: 'New page',
  padNewText: 'Text page',
  padNewInk: 'Pen page',
  padPageOf: 'Page {n} of {m}',
  padPrevPage: 'Newer page',
  padNextPage: 'Older page',
  padPagesFull: 'At most 40 pages — delete one to make room.',
  padPlaceholder: 'Write here …',
  padTime: 'Time',
  padTimeTitle: 'Insert the time',
  padSection: 'Section',
  padSectionTitle: 'Insert a phase of the match',
  padSectionPre: 'Pre-game',
  padSectionProtocol: 'Protocol',
  padSectionSet: 'Set {n}',
  padSectionBreak: 'Between sets',
  padSectionPost: 'After game',
  padEmpty: 'No pages yet. Start writing — or pick up the pen.',
  padDeletePage: 'Delete page',
  padDeleteTitle: 'Delete page?',
  padDeleteMsg: 'The page is deleted on all your devices.',
  padSaving: 'Saving…',
  padSaved: 'Saved',
  padSynced: 'Backed up on the server',
  padSyncPending: 'Server follows once online',
  padSyncFailed: 'The server refused the page',
  padSyncRejected: 'The server refused this page ({reason}) — edit it to try again.',
  padNoStore: 'This device cannot store the notebook (private mode?).',
  padServerOnly: 'Backed up on the server only — this device stores nothing.',
  padSaveFailed: 'Could not save the page — storage full?',
  padInsert: 'Insert…',
  padInsertTitle: 'Insert',
  padInsertFor: 'For: {role} · {name} (current form)',
  padInsertTarget: 'Target',
  padInsertRemarks: 'Remarks',
  padInsertHighlights: 'Highlights & potential',
  padInsertImprovements: 'Improvement',
  padInsertGoals: 'Goals',
  padInsertTips: 'Tips & Tricks (e-mail only)',
  padInsertCount1: '1 page → {field} ({role})',
  padInsertCountN: '{n} pages → {field} ({role})',
  padInsertNone: 'No page selected',
  padImportWarn: 'Inserted text becomes part of the feedback and is e-mailed to the referee with the PDF.',
  padImportWarnTips: 'Tips & Tricks go to the referee by e-mail only, not into the feedback.',
  padInserted1: '1 page inserted into "{field}" — goes to the referee with the feedback.',
  padInsertedN: '{n} pages inserted into "{field}" — goes to the referee with the feedback.',
  padInsertAgainTitle: 'Insert again?',
  padInsertAgainMsg: 'This page was already inserted into "{field}".',
  padUsedIn: 'inserted → {field} ({role}) · {label}',
  padShowUsed: 'Show inserted pages',
  padInkOnly: 'Pen page — cannot be inserted, view only.',
  padInkNotImported: 'Pen pages are not inserted — they are for reading back.',
  padReviewOnly: 'Observation sent — the notebook stays private; inserting is no longer possible here.',
  padPenBlack: 'Pen',
  padPenRed: 'Red',
  padEraser: 'Eraser',
  padUndo: 'Undo',
  padClearPage: 'Clear page',
  padClearPageTitle: 'Clear page?',
  padClearPageMsg: 'Every stroke on this page is removed.',
  padFinger: 'Finger',
  padFingerOn: 'Finger draws',
  padFingerOff: 'Pen only',
  padPenSeen: 'Pen detected — the finger no longer draws.',
  padPageFull: 'Page full — please start a new page.',
  padInkLoading: 'Loading pen page…',
  padScribbleHint: 'Missing strokes? On iPad: Settings → Apple Pencil → Scribble off.',
  padFull: 'Fullscreen',
  padFullExit: 'Exit fullscreen',
  padCourt: 'Court',
  padTextPageShort: 'Text',
  padInkPageShort: 'Pen',
  padCancel: 'Cancel',
  padClose: 'Close',
  padBack: 'Back to the pages',
};

export const PAD_STRINGS = { DE, EN } satisfies Record<PadLang, Record<keyof typeof DE, string>>;
export type PadStrings = typeof DE;
