// Words for the statistics — the dashboard, the deck and the PDF read the
// same numbers and must call them the same thing. German is the commission's
// language; English follows the console's toggle.
import type { Lang } from './appTime';
import { seasonLabel } from './season';
import { groupLabel } from './coacheeGroup';
import { SECTIONS_1SR_DE, SECTIONS_1SR_EN, SECTIONS_2SR_DE, SECTIONS_2SR_EN } from '../types';
import type { StatRole } from './statistics';

export const STAT_STR = {
  DE: {
    tab: 'Statistik',
    title: 'Statistik',
    // section headers
    secOverview: 'Überblick',
    secOverviewHint: 'Die Saison auf einen Blick.',
    secObservations: 'Beobachtungen',
    secObservationsHint: 'Wann, von wem, bei wem — und wie weit die Saison ist.',
    secGrades: 'Noten',
    secGradesHint: 'Wie bewertet wurde: verteilt, pro Abschnitt, pro Kriterium.',
    secOutcomes: 'Beurteilungen',
    secOutcomesHint: 'Was die Coaches am Ende des Formulars ankreuzen.',
    secGames: 'Spiele',
    secGamesHint: 'Was in den Hallen gesehen wurde.',
    secWriting: 'Schreiben & Prozess',
    secWritingHint: 'Wie viel geschrieben, wie schnell eingereicht — und ein paar Zahlen zum Schmunzeln.',
    // One line under every block: what it shows, in plain words.
    desc: {
      months: 'Beobachtungen nach Spielmonat, 1. und 2. SR gestapelt.',
      coverage: 'Wie viele Coachees der Liste 0, 1, 2 oder 3+ Mal besucht wurden.',
      roles: 'Wie sich die Beobachtungen auf 1. und 2. SR verteilen.',
      rcs: 'Pro Coach: Beobachtungen, Coachees, Spiele und Ø vergebene Note; der Balken zeigt den Stand gegenüber dem Pensum.',
      groups: 'Beobachtungen pro Coachee-Gruppe, mit Anzahl Coachees und Ø Note.',
      levels: 'Beobachtungen pro Niveau, mit Anzahl Coachees und Ø Note; darunter die Ø Note pro Stufe, A links bis E rechts.',
      gradeSummary: 'Ø aller vergebenen Noten, Anteil C und A/B, und pro Rolle. C = Normalfall.',
      gradeMonth: 'Ø Note nach Spielmonat; die gestrichelte Linie ist C, der Normalfall. Hohl = weniger als 3 Beobachtungen.',
      sections: 'Ø Note pro Abschnitt des Formulars, pro Rolle — A links bis E rechts, der graue Strich ist C (Normalfall).',
      criteria: 'Ø Note pro Kriterium des Formulars — A links bis E rechts, der graue Strich ist C (Normalfall).',
      trendTotal: 'Coachees mit 2+ Beobachtungen: ist die letzte Note besser, gleich oder schlechter als die erste? Weniger als ein halber Notenschritt gilt als gleich.',
      trendLevel: 'Dasselbe, nach Niveau der letzten Beobachtung.',
      trendGroup: 'Dasselbe, pro Coachee-Gruppe.',
      einstufung: 'Was angekreuzt wurde: Einstufung (Rückstufung ↓ · gleich ✓ · Beförderung ↑) und Motivation (tief ↓ · in Ordnung ✓ · hoch ↑).',
      spielniveau: 'Wie schwierig die Coaches das Spiel einschätzten.',
      secondBesuch: 'Ob die Coaches einen weiteren Besuch wünschen.',
      games: 'Sätze, Punkte, geschätzte Hallenzeit, Entscheidungssätze, das längste Spiel, gesehene Hallen und Teams.',
      leagues: 'Beobachtungen pro Liga, und Herren- gegen Damenspiele.',
      when: 'An welchem Wochentag und zu welcher Anspielzeit die beobachteten Spiele stattfanden.',
      writing: 'Wie viel in die vier Textfelder geschrieben wurde und wie oft jedes ausgefüllt war.',
      process: 'Wie schnell nach dem Spiel eingereicht wurde, wie viele unterschrieben sind und wie vollständig benotet.',
      fun: 'Ein paar Rekorde der Saison.',
    },
    hint: 'Die Saison in Zahlen — aus den eingereichten Beobachtungen. Nur Zählungen und Durchschnitte; Bemerkungen bleiben auf dem Server.',
    season: 'Saison',
    all: 'alle',
    rc: 'Referee Coach',
    group: 'Gruppe',
    level: 'Niveau',
    role: 'Rolle',
    compare: 'Vergleich mit Vorsaison',
    export: 'Export',
    exportPptx: 'PPT',
    exportPdf: 'PDF',
    exportHint: 'Foliensatz aus den Zahlen oben, mit den gesetzten Filtern.',
    exportLang: 'Sprache der Folien',
    optRcGrades: 'Folie „Noten pro Coach" (wer streng bewertet)',
    optLeagues: 'Folie „Ligen"',
    exporting: 'Wird erstellt …',
    exportFailed: 'Export fehlgeschlagen',
    loading: 'Wird geladen …',
    none: 'Keine Beobachtungen in dieser Saison.',
    nObs: (n: number) => `${n} Beob.`,
    tooFew: (n: number) => `n = ${n}`,
    thinNote: 'weniger als 3 Beobachtungen — hohl gezeichnet, mit Vorsicht lesen',
    prev: 'Vorsaison',
    deltaVs: (s: string) => `gegenüber ${s}`,
    // tiles
    observations: 'Beobachtungen',
    coacheesVisited: 'Coachees besucht',
    ofRoster: (n: number, total: number) => `von ${total}`,
    activeRcs: 'Aktive RC',
    pensum: 'Pensum',
    avgGrade: 'Ø Note',
    normalCase: 'C = Normalfall',
    sets: 'Sätze',
    games: (n: number) => `${n} Spiele`,
    points: 'Punkte',
    hours: (h: number) => `≈ ${h} h Halle`,
    words: 'Wörter',
    perObs: 'Ø pro Beob.',
    // blocks
    perMonth: 'Beobachtungen pro Monat',
    histogram: 'Notenverteilung',
    histogramHint: 'Jede vergebene Note, A bis E (± zählen zu ihrem Buchstaben)',
    shareC: 'Anteil C',
    shareB: 'Anteil B oder besser',
    sections: 'Ø Note pro Abschnitt',
    criteria: 'Ø Note pro Kriterium',
    role1: '1. SR',
    role2: '2. SR',
    perRc: 'Pro Referee Coach',
    perGroup: 'Pro Gruppe',
    perLevel: 'Pro Niveau',
    perStufe: 'Pro Stufe',
    perLevelStufe: 'Ø Note pro Niveau und Stufe',
    gradePerMonth: 'Ø Note pro Monat',
    perLeague: 'Ligen',
    coverage: 'Abdeckung',
    coverageHint: 'Coachees nach Anzahl Besuche',
    visits: (k: string) => (k === '3+' ? '3+ Besuche' : k === '1' ? '1 Besuch' : `${k} Besuche`),
    outcomes: 'Beurteilungen',
    einstufung: 'Einstufung',
    motivation: 'Motivation',
    difficulty: 'Spielniveau',
    secondVisit: 'Zweiter Besuch',
    srGoal: 'SR-Ziel',
    gamesBlock: 'Spiele',
    setsPerGame: 'Sätze pro Spiel',
    deciders: 'Entscheidungssätze',
    longestGame: 'Längstes Spiel',
    hallsSeen: 'Hallen',
    teamsSeen: 'Teams',
    estHours: 'Stunden in der Halle (geschätzt)',
    writing: 'Schreiben',
    chars: 'Zeichen',
    wordsMedian: 'Median pro Beob.',
    longestRemark: 'Längste Beobachtung',
    pagesA4: 'A4-Seiten (≈ 500 Wörter)',
    filled: 'Blöcke ausgefüllt',
    highlights: 'Highlights',
    improvements: 'Verbesserungen',
    goals: 'Ziele',
    process: 'Prozess',
    filingMedian: 'Median bis Einreichung',
    days: (d: number) => (d === 1 ? '1 Tag' : `${d} Tage`),
    sameDay: 'Gleicher Tag',
    late: 'Nach 7+ Tagen',
    signedRef: 'Von SR unterschrieben',
    signedRc: 'Vom RC unterschrieben',
    language: 'Sprache',
    completeness: 'Kriterien bewertet',
    fun: 'Wussten Sie?',
    na: 'k. A.',
    busiestDay: 'Meiste Beobachtungen an einem Tag',
    topHall: 'Meistbesuchte Halle',
    topCoachee: 'Meistbesuchter Coachee',
    topWriter: 'Meiste Wörter',
    firstLast: 'Erste / letzte Beobachtung',
    weekday: 'Wochentag',
    hour: 'Anspielzeit',
    goalCol: 'Pensum',
    planned: 'geplant',
    outstanding: 'offen',
    coacheesCol: 'Coachees',
    gamesCol: 'Spiele',
    setsCol: 'Sätze',
    nCoachees: (n: number) => `${n} ${n === 1 ? 'Coachee' : 'Coachees'}`,
    nGames: (n: number) => `${n} ${n === 1 ? 'Spiel' : 'Spiele'}`,
    nSets: (n: number) => `${n} ${n === 1 ? 'Satz' : 'Sätze'}`,
    wordsCol: 'Wörter',
    gradeCol: 'Ø Note',
    method: 'Zählregeln',
    methodLines: [
      'Saison = Spieldatum (Sept.–Apr.), nie das Einreichdatum. Testspiele ohne Coachee zählen nicht.',
      'Ein Spiel mit beiden SR beurteilt: zwei Beobachtungen, ein Spiel — Sätze und Punkte einmal.',
      'Noten in Buchstaben A bis E: Plus und Minus zählen zum jeweiligen Buchstaben. C ist der Normalfall; ein Durchschnitt aus weniger als 3 Beobachtungen ist hohl gezeichnet und trägt sein n.',
      'Niveau und Gruppe wie auf dem Formular erfasst; ein Coachee in zwei Gruppen zählt in beiden.',
      'Wörter: Bemerkungen, Highlights, Verbesserungen und Ziele, ohne Formatierung.',
    ],
    stand: 'Stand',
    deckTitle: 'SR-Coaching — Statistik',
    deckSubtitle: (s: string) => `Saison ${s}`,
    deckNumbers: 'Die Saison in Zahlen',
    deckStrongWeak: 'Stärkste und schwächste Kriterien',
    deckStrong: 'Stärkste',
    deckWeak: 'Schwächste',
    swTitle: 'Stärken & Schwächen pro Niveau',
    swHint: 'Ein Niveau wählen: jedes Kriterium gegenüber dem eigenen Ø dieses Niveaus (gestrichelte Linie). Links davon = besser bewertet. Markiert ab 3 Beobachtungen und ⅓ Note Abstand — auch innerhalb desselben Buchstabens.',
    swLevelAvg: (level: string) => `Ø ${level}`,
    swTooThin: 'Noch kein Kriterium mit 3 Beobachtungen — nichts markiert.',
    swAvgRow: 'Ø des Niveaus',
    swCriterion: 'Kriterium',
    swThin: 'hohl = weniger als 3 Beobachtungen, nicht markiert',
    swStronger: 'stärker',
    swClearlyStronger: 'deutlich stärker',
    swWeaker: 'schwächer',
    swClearlyWeaker: 'deutlich schwächer',
    swVsAvg: 'ggü. Ø',
    swStrengths: 'Stärken',
    swWeaknesses: 'Schwächen',
    swNone: 'keine deutlichen',
    swDeckHint: 'Gegenüber dem Ø des Niveaus auf demselben Formular · ab 3 Beobachtungen, mindestens 1/3 Note Abstand',
    deckLevelGroup: 'Noten nach Niveau und Gruppe',
    deckCompare: 'Im Vergleich zur Vorsaison',
    deckRcGrades: 'Noten pro Coach',
    deckRcGradesHint: 'Durchschnitt der vergebenen Noten — intern.',
    filtersLine: 'Filter',
    // deck: agenda, chapters, the export menu
    deckAgenda: 'Inhalt',
    chapterTitle: (k: string): string => ({ overview: 'Überblick', grades: 'Noten', outcomes: 'Beurteilungen & Entwicklung', games: 'Spiele & Schreiben', levels: 'Nach Niveau', groups: 'Nach Gruppe' } as Record<string, string>)[k] ?? k,
    chapterHint: (k: string): string => ({ overview: 'Die Saison in Zahlen: wer, wann, wie viel.', grades: 'Wie bewertet wurde — in Buchstaben A bis E.', outcomes: 'Einstufung, Motivation, weiterer Besuch und wer sich verbessert hat.', games: 'Die Spiele hinter den Beobachtungen und was geschrieben wurde.', levels: 'Jedes Niveau für sich.', groups: 'Jede Gruppe für sich.' } as Record<string, string>)[k] ?? '',
    sectionLabel: (k: string): string => ({ numbers: 'Die Saison in Zahlen', months: 'Beobachtungen pro Monat', coverage: 'Abdeckung', rcs: 'Pro Referee Coach', compare: 'Vergleich Vorsaison', fun: 'Wusstest du?', histogram: 'Notenverteilung & pro Monat', sections: 'Ø pro Abschnitt', criteria: 'Stärkste / schwächste Kriterien', levelGroup: 'Noten nach Niveau und Gruppe', rcGrades: 'Noten pro Coach (intern)', outcomes: 'Beurteilungen', trend: 'Entwicklung', games: 'Spiele', writing: 'Schreiben', leagues: 'Ligen', levelSets: 'Folien pro Niveau (inkl. Stärken & Schwächen)', groupSets: 'Folien pro Gruppe', method: 'Zählregeln' } as Record<string, string>)[k] ?? k,
    exportSections: 'Inhalt',
    exportAll: 'Alle',
    exportNone: 'Keine',
    exportFormat: 'Format',
    format169: '16:9 (Bildschirm)',
    formatA4: 'A4 quer (Druck)',
    // trend
    trendTitle: 'Entwicklung',
    trendHint: 'Coachees mit zwei oder mehr benoteten Beobachtungen: die erste gegen die letzte.',
    trendImproved: 'Besser',
    trendSame: 'Gleich',
    trendWorse: 'Schlechter',
    trendCoachees: 'Coachees mit 2+ Beob.',
    trendAvg: 'Ø Veränderung',
    trendNone: 'Erscheint, sobald ein Coachee zwei benotete Beobachtungen hat.',
    trendCol: 'Trend',
    trendBand: 'Weniger als ein halber Notenschritt gilt als gleich.',
    // deck: the per-level and per-group sets
    deckSetLevel: (l: string) => `Niveau ${l}`,
    deckSetGroup: (g: string) => `Gruppe: ${g}`,
    deckSetsLevel: 'Nach Niveau',
    deckSetsGroup: 'Nach Gruppe',
    deckSetsHint: 'Eine Folienserie pro Niveau bzw. Gruppe; leere sind weggelassen.',
    optSlices: 'Folien pro Niveau und pro Gruppe',
    // bottom filter bar + the comparison by level / group
    groupBy: 'Filter',
    noFilter: 'Kein Filter',
    byLevel: 'Niveau',
    byGroup: 'Gruppe',
    allOfLevel: (niv: string) => `Ganzes ${niv}`,
    compareTitle: (dim: 'level' | 'group'): string => (dim === 'level' ? 'Nach Niveau' : 'Nach Gruppe'),
    compareHint: 'Jede Zeile ist ein eigener Ausschnitt — antippen, um danach zu filtern.',
    compareObs: 'Beob.',
    compareCoverage: 'Besucht',
    comparePromotion: 'Beförd.',
    comparePromotionHint: 'Anteil Einstufung ↑ (Beförderung)',
    compareFurther: 'Weiterer Besuch',
    compareFurtherShort: 'Weit. Besuch',
    compareFurtherHint: 'Anteil «Weiterer Besuch: Y»',
    compareEmpty: 'Keine Daten für diese Auswahl.',
    generated: 'Erstellt mit dem SR-Coaching-Tool',
  },
  EN: {
    tab: 'Statistics',
    title: 'Statistics',
    secOverview: 'Overview',
    secOverviewHint: 'The season at a glance.',
    secObservations: 'Observations',
    secObservationsHint: 'When, by whom, of whom — and how far the season has come.',
    secGrades: 'Grades',
    secGradesHint: 'How the coaches graded: distribution, per section, per criterion.',
    secOutcomes: 'Assessments',
    secOutcomesHint: 'What the coaches tick at the end of the form.',
    secGames: 'Games',
    secGamesHint: 'What was watched in the halls.',
    secWriting: 'Writing & process',
    secWritingHint: 'How much was written, how quickly filed — and a few numbers to smile at.',
    // One line under every block: what it shows, in plain words.
    desc: {
      months: 'Observations by month of the game, 1st and 2nd referee stacked.',
      coverage: 'How many Coachees on the roster were visited 0, 1, 2 or 3+ times.',
      roles: 'How the observations split between 1st and 2nd referee.',
      rcs: 'Per coach: observations, Coachees, games and the average grade given; the bar is progress towards their goal.',
      groups: 'Observations per Coachee group, with the number of Coachees and their average grade.',
      levels: 'Observations per level, with the number of Coachees and their average grade; below, the average grade per Stufe, A left to E right.',
      gradeSummary: 'The average of every grade given, the share of C and of A/B, and per role. C = normal case.',
      gradeMonth: 'Average grade by month of the game; the dashed line is C, the normal case. Hollow = fewer than 3 observations.',
      sections: 'Average grade per section of the form, per role — A left to E right, the grey mark is C (normal case).',
      criteria: 'Average grade per criterion of the form — A left to E right, the grey mark is C (normal case).',
      trendTotal: 'Coachees with 2+ observations: is their latest grade better, the same or worse than their first? Less than half a grade step counts as the same.',
      trendLevel: 'The same, by level of the latest observation.',
      trendGroup: 'The same, per Coachee group.',
      einstufung: 'What the coaches ticked: classification (relegation ↓ · same ✓ · promotion ↑) and motivation (low ↓ · in order ✓ · high ↑).',
      spielniveau: 'How difficult the coaches rated the game.',
      secondBesuch: 'Whether the coaches want a further visit.',
      games: 'Sets, points, estimated time in the hall, deciding sets, the longest game, halls and teams seen.',
      leagues: 'Observations per league, and men\'s against women\'s games.',
      when: 'On which weekday and at what kick-off time the observed games were played.',
      writing: 'How much was written in the form\'s four text fields, and how often each was filled.',
      process: 'How quickly forms were filed after the game, how many are signed, and how completely graded.',
      fun: 'A few records of the season.',
    },
    hint: 'The season in numbers, from the filed observations. Counts and averages only; the remarks stay on the server.',
    season: 'Season',
    all: 'all',
    rc: 'Referee Coach',
    group: 'Group',
    level: 'Level',
    role: 'Role',
    compare: 'Compare with previous season',
    export: 'Export',
    exportPptx: 'PPT',
    exportPdf: 'PDF',
    exportHint: 'A slide deck from the numbers above, with the filters set.',
    exportLang: 'Slide language',
    optRcGrades: 'Slide "Grades per coach" (who grades strictly)',
    optLeagues: 'Slide "Leagues"',
    exporting: 'Building …',
    exportFailed: 'Export failed',
    loading: 'Loading …',
    none: 'No observations in this season.',
    nObs: (n: number) => `${n} obs.`,
    tooFew: (n: number) => `n = ${n}`,
    thinNote: 'fewer than 3 observations — drawn hollow, read with care',
    prev: 'Previous season',
    deltaVs: (s: string) => `vs. ${s}`,
    observations: 'Observations',
    coacheesVisited: 'Coachees visited',
    ofRoster: (n: number, total: number) => `of ${total}`,
    activeRcs: 'Active RCs',
    pensum: 'Goal',
    avgGrade: 'Avg. grade',
    normalCase: 'C = normal case',
    sets: 'Sets',
    games: (n: number) => `${n} games`,
    points: 'Points',
    hours: (h: number) => `≈ ${h} h in the hall`,
    words: 'Words',
    perObs: 'avg. per obs.',
    perMonth: 'Observations per month',
    histogram: 'Grade distribution',
    histogramHint: 'Every rating given, A to E (± count as their letter)',
    shareC: 'Share of C',
    shareB: 'Share B or better',
    sections: 'Avg. grade per section',
    criteria: 'Avg. grade per criterion',
    role1: '1st referee',
    role2: '2nd referee',
    perRc: 'Per Referee Coach',
    perGroup: 'Per group',
    perLevel: 'Per level',
    perStufe: 'Per Stufe',
    perLevelStufe: 'Avg. grade per level and Stufe',
    gradePerMonth: 'Avg. grade per month',
    perLeague: 'Leagues',
    coverage: 'Coverage',
    coverageHint: 'Coachees by number of visits',
    visits: (k: string) => (k === '3+' ? '3+ visits' : k === '1' ? '1 visit' : `${k} visits`),
    outcomes: 'Assessments',
    einstufung: 'Classification',
    motivation: 'Motivation',
    difficulty: 'Game difficulty',
    secondVisit: 'Second visit',
    srGoal: 'Referee goal',
    gamesBlock: 'Games',
    setsPerGame: 'Sets per game',
    deciders: 'Deciding sets',
    longestGame: 'Longest game',
    hallsSeen: 'Halls',
    teamsSeen: 'Teams',
    estHours: 'Hours in the hall (estimated)',
    writing: 'Writing',
    chars: 'Characters',
    wordsMedian: 'Median per obs.',
    longestRemark: 'Longest observation',
    pagesA4: 'A4 pages (≈ 500 words)',
    filled: 'Blocks filled',
    highlights: 'Highlights',
    improvements: 'Improvements',
    goals: 'Goals',
    process: 'Process',
    filingMedian: 'Median until filed',
    days: (d: number) => (d === 1 ? '1 day' : `${d} days`),
    sameDay: 'Same day',
    late: 'After 7+ days',
    signedRef: 'Signed by referee',
    signedRc: 'Signed by RC',
    language: 'Language',
    completeness: 'Criteria rated',
    fun: 'Did you know?',
    na: 'N/A',
    busiestDay: 'Most observations on one day',
    topHall: 'Most-visited hall',
    topCoachee: 'Most-observed coachee',
    topWriter: 'Most words',
    firstLast: 'First / last observation',
    weekday: 'Weekday',
    hour: 'Kick-off',
    goalCol: 'Goal',
    planned: 'planned',
    outstanding: 'open',
    coacheesCol: 'Coachees',
    gamesCol: 'Games',
    setsCol: 'Sets',
    nCoachees: (n: number) => `${n} ${n === 1 ? 'Coachee' : 'Coachees'}`,
    nGames: (n: number) => `${n} ${n === 1 ? 'game' : 'games'}`,
    nSets: (n: number) => `${n} ${n === 1 ? 'set' : 'sets'}`,
    wordsCol: 'Words',
    gradeCol: 'Avg. grade',
    method: 'Counting rules',
    methodLines: [
      'Season = game date (Sept–Apr), never the filing date. Test games without a coachee do not count.',
      'A game with both referees assessed: two observations, one game — sets and points counted once.',
      'Grades in letters A to E: plus and minus count as the letter they belong to. C is the normal case; an average from fewer than 3 observations is drawn hollow and carries its n.',
      'Level and group as recorded on the form; a coachee in two groups counts in both.',
      'Words: remarks, highlights, improvements and goals, formatting stripped.',
    ],
    stand: 'As of',
    deckTitle: 'Referee Coaching — Statistics',
    deckSubtitle: (s: string) => `Season ${s}`,
    deckNumbers: 'The season in numbers',
    deckStrongWeak: 'Strongest and weakest criteria',
    deckStrong: 'Strongest',
    deckWeak: 'Weakest',
    swTitle: 'Strengths & weaknesses per level',
    swHint: 'Pick a level: each criterion against that level\'s own average (dashed line). Left of the line = graded better. Marked from 3 observations and ⅓ of a grade apart — even within the same letter.',
    swLevelAvg: (level: string) => `${level} average`,
    swTooThin: 'No criterion has 3 observations yet — nothing marked.',
    swAvgRow: 'Level average',
    swCriterion: 'Criterion',
    swThin: 'hollow = fewer than 3 observations, not marked',
    swStronger: 'stronger',
    swClearlyStronger: 'clearly stronger',
    swWeaker: 'weaker',
    swClearlyWeaker: 'clearly weaker',
    swVsAvg: 'vs avg.',
    swStrengths: 'Strengths',
    swWeaknesses: 'Weaknesses',
    swNone: 'none clear',
    swDeckHint: 'Against the level\'s average on the same form · from 3 observations, at least 1/3 of a grade apart',
    deckLevelGroup: 'Grades by level and group',
    deckCompare: 'Compared with the previous season',
    deckRcGrades: 'Grades per coach',
    deckRcGradesHint: 'Average of the grades given — internal.',
    filtersLine: 'Filters',
    // deck: agenda, chapters, the export menu
    deckAgenda: 'Contents',
    chapterTitle: (k: string): string => ({ overview: 'Overview', grades: 'Grades', outcomes: 'Assessments & trend', games: 'Games & writing', levels: 'By level', groups: 'By group' } as Record<string, string>)[k] ?? k,
    chapterHint: (k: string): string => ({ overview: 'The season in numbers: who, when, how much.', grades: 'How the coaches graded — in letters A to E.', outcomes: 'Rating, motivation, further visits and who improved.', games: 'The games behind the observations and what was written.', levels: 'Each level on its own.', groups: 'Each group on its own.' } as Record<string, string>)[k] ?? '',
    sectionLabel: (k: string): string => ({ numbers: 'The season in numbers', months: 'Observations per month', coverage: 'Coverage', rcs: 'Per referee coach', compare: 'Previous season', fun: 'Did you know?', histogram: 'Grade distribution & per month', sections: 'Avg. per section', criteria: 'Strongest / weakest criteria', levelGroup: 'Grades by level and group', rcGrades: 'Grades per coach (internal)', outcomes: 'Assessments', trend: 'Trend', games: 'Games', writing: 'Writing', leagues: 'Leagues', levelSets: 'Slides per level (incl. strengths & weaknesses)', groupSets: 'Slides per group', method: 'Counting rules' } as Record<string, string>)[k] ?? k,
    exportSections: 'Contents',
    exportAll: 'All',
    exportNone: 'None',
    exportFormat: 'Format',
    format169: '16:9 (screen)',
    formatA4: 'A4 landscape (print)',
    // trend
    trendTitle: 'Trend',
    trendHint: 'Coachees with two or more graded observations: the first against the latest.',
    trendImproved: 'Better',
    trendSame: 'Same',
    trendWorse: 'Worse',
    trendCoachees: 'Coachees with 2+ obs.',
    trendAvg: 'Avg. change',
    trendNone: 'Appears once a coachee has two graded observations.',
    trendCol: 'Trend',
    trendBand: 'Less than half a grade step counts as the same.',
    // deck: the per-level and per-group sets
    deckSetLevel: (l: string) => `Level ${l}`,
    deckSetGroup: (g: string) => `Group: ${g}`,
    deckSetsLevel: 'By level',
    deckSetsGroup: 'By group',
    deckSetsHint: 'One set of slides per level or group; empty ones are left out.',
    optSlices: 'Slides per level and per group',
    // bottom filter bar + the comparison by level / group
    groupBy: 'Filter',
    noFilter: 'No filter',
    byLevel: 'Level',
    byGroup: 'Group',
    allOfLevel: (niv: string) => `All of ${niv}`,
    compareTitle: (dim: 'level' | 'group'): string => (dim === 'level' ? 'By level' : 'By group'),
    compareHint: 'Each row is its own slice — tap one to filter by it.',
    compareObs: 'Obs.',
    compareCoverage: 'Visited',
    comparePromotion: 'Promo.',
    comparePromotionHint: 'Share rated ↑ (promotion)',
    compareFurther: 'Further visit',
    compareFurtherShort: 'Further visit',
    compareFurtherHint: 'Share "further visit: Y"',
    compareEmpty: 'No data for this selection.',
    generated: 'Generated with the SR-Coaching tool',
  },
};
export type StatStrings = typeof STAT_STR['DE'];
export const statStrings = (lang: Lang): StatStrings => STAT_STR[lang];

// ── Labels for keys the server sends ─────────────────────────────────────────
const MONTHS = {
  DE: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
  EN: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
};
export function monthLabel(key: string, lang: Lang): string {
  const m = Number(key.split('-')[1]);
  return MONTHS[lang][m - 1] ?? key;
}
const WEEKDAYS = { DE: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'], EN: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] };
export function weekdayKeyLabel(key: string, lang: Lang): string {
  return WEEKDAYS[lang][Number(key) - 1] ?? key;
}
export function roleLabel(role: string, lang: Lang): string {
  return role === '2SR' ? STAT_STR[lang].role2 : STAT_STR[lang].role1;
}
export function categoryLabel(key: string, lang: Lang): string {
  const de = lang === 'DE';
  return key === 'H' ? (de ? 'Herren' : 'Men') : (de ? 'Damen' : 'Women');
}
export function groupKeyLabel(key: string, lang: Lang): string {
  if (!key) return lang === 'DE' ? 'ohne Gruppe' : 'no group';
  return groupLabel(key, lang) || key;
}
export function levelKeyLabel(key: string, lang: Lang): string {
  return key || (lang === 'DE' ? 'ohne Niveau' : 'no level');
}

export const OUTCOME_LABELS = {
  einstufung: {
    DE: { up: 'Beförderung', check: 'Gleich', down: 'Rückstufung' },
    EN: { up: 'Promotion', check: 'Same level', down: 'Relegation' },
  },
  motivation: {
    DE: { up: 'Hoch', check: 'In Ordnung', down: 'Tief' },
    EN: { up: 'High', check: 'In order', down: 'Low' },
  },
  spielniveau: {
    DE: { leicht: 'Leicht', normal: 'Normal', schwierig: 'Schwierig' },
    EN: { leicht: 'Easy', normal: 'Normal', schwierig: 'Hard' },
  },
  secondBesuch: {
    DE: { Y: 'Ja', N: 'Nein' },
    EN: { Y: 'Yes', N: 'No' },
  },
} as const;
export const OUTCOME_ORDER = {
  einstufung: ['up', 'check', 'down'],
  motivation: ['up', 'check', 'down'],
  spielniveau: ['leicht', 'normal', 'schwierig'],
  secondBesuch: ['Y', 'N'],
} as const;
// Green is the good end, red the one that asks for attention, blue the middle —
// the commission's own reading of these three-way ticks. "Second visit: yes"
// is not bad news, so it takes the neutral blue and "no" the green.
export const OUTCOME_GREEN = '#1f7a4d';
/** Sequential blue, light → dark (fewer → more), validated: adjacent ΔE ≥ 16.5. */
export const SEQ_BLUE = ['#c3daf7', '#6aa6ea', '#2466c0', '#132f5c'] as const;
/** The neutral middle of a diverging bar (✓ / same). */
export const NEUTRAL = '#d6d3d1';
export const OUTCOME_BLUE = '#2a78d6';
export const OUTCOME_RED = '#e2001a'; // brand red, as --color-brand
export const OUTCOME_COLORS: Record<keyof typeof OUTCOME_ORDER, Record<string, string>> = {
  einstufung: { up: OUTCOME_GREEN, check: OUTCOME_BLUE, down: OUTCOME_RED },
  motivation: { up: OUTCOME_GREEN, check: OUTCOME_BLUE, down: OUTCOME_RED },
  spielniveau: { leicht: OUTCOME_GREEN, normal: OUTCOME_BLUE, schwierig: OUTCOME_RED },
  secondBesuch: { Y: OUTCOME_BLUE, N: OUTCOME_GREEN },
};
export function outcomeColor(kind: keyof typeof OUTCOME_ORDER, key: string): string {
  return OUTCOME_COLORS[kind][key] ?? OUTCOME_BLUE;
}

export function outcomeLabel(kind: keyof typeof OUTCOME_LABELS, key: string, lang: Lang): string {
  const table = OUTCOME_LABELS[kind][lang] as Record<string, string>;
  return table[key] ?? key;
}
export function srGoalLabel(key: string, lang: Lang): string {
  if (key === 'Verbleib' || key === 'same_level') return lang === 'DE' ? 'Verbleib' : 'Remain';
  return key;
}

// ── The forms' own words for their sections and criteria ─────────────────────
function sectionsFor(role: StatRole, lang: Lang) {
  if (role === '2SR') return lang === 'DE' ? SECTIONS_2SR_DE : SECTIONS_2SR_EN;
  return lang === 'DE' ? SECTIONS_1SR_DE : SECTIONS_1SR_EN;
}
export function sectionTitle(role: StatRole, index: number, lang: Lang): string {
  return sectionsFor(role, lang)[index]?.title ?? `${index + 1}`;
}
export function criterionLabel(role: StatRole, id: string, lang: Lang): string {
  for (const section of sectionsFor(role, lang)) {
    const item = section.items.find((it) => it.id === id);
    if (item) return item.label;
  }
  return id;
}
export function sectionCount(role: StatRole): number {
  return sectionsFor(role, 'DE').length;
}

export const seasonName = seasonLabel;
