#!/usr/bin/env bash
# Write the winget manifests of the installed app for one release.
#
#   deploy/native/winget/update-manifests.sh VERSION [--file PATH]
#
# Writes manifests/l/Lucanepa/SVRZRC/<VERSION>/ — the same path as in
# microsoft/winget-pkgs, so the folder is copied into a fork as it is — and
# removes older version folders here (winget-pkgs keeps every version; this
# repo keeps the one to submit). The pattern is OpenVolley's
# (github.com/Lucanepa/openvolley, escoresheet/packaging/winget/README.md).
#
# The installer's SHA-256 comes from the GitHub release (`native-v<VERSION>`,
# the NSIS `-setup.exe`), or from a local copy with --file.
#
# What Tauri's NSIS installer does, and so what the manifest says: installMode
# is Tauri's default `currentUser` — no administrator prompt, installed to
# %LOCALAPPDATA%\SVRZ RC — so Scope is user. Apps & features names it by
# productName ("SVRZ RC") with bundle.publisher ("Luca Canepa"); winget matches
# a copy installed from the release page by that and offers it upgrades. The
# app also updates itself (tauri-plugin-updater); both lead to the same version.
set -euo pipefail
REPO=Lucanepa/svrz_rc
MANIFEST_VERSION=1.28.0
ID=Lucanepa.SVRZRC
HERE=$(cd "$(dirname "$0")" && pwd)
die() { echo "update-manifests: $*" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: $0 VERSION [--file PATH]"
version=$1; shift
file=''
while [ $# -gt 0 ]; do
  case $1 in
    --file) file=${2:?}; shift 2 ;;
    *) die "unknown option $1" ;;
  esac
done
[[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "version must look like 1.0.0"
tag=native-v$version

release=$(gh release view "$tag" -R "$REPO" --json assets,publishedAt) || die "no release $tag"
url=$(python3 -c 'import json,sys; d=json.loads(sys.argv[1]); print(next(a["url"] for a in d["assets"] if a["name"].endswith("_x64-setup.exe")))' "$release") \
  || die "$tag has no _x64-setup.exe"
date=$(python3 -c 'import json,sys; print(json.loads(sys.argv[1])["publishedAt"][:10])' "$release")
if [ -z "$file" ]; then
  tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
  curl -fsSL --retry 3 -o "$tmp/setup.exe" "$url"
  file=$tmp/setup.exe
fi
sha=$(sha256sum "$file" | cut -d' ' -f1 | tr 'a-f' 'A-F')

root=$HERE/manifests/l/Lucanepa/SVRZRC
find "$root" -mindepth 1 -maxdepth 1 -type d ! -name "$version" -exec rm -rf {} + 2>/dev/null || true
out=$root/$version
mkdir -p "$out"
head() { printf '# yaml-language-server: $schema=https://aka.ms/winget-manifest.%s.%s.schema.json\n# Generated by deploy/native/winget/update-manifests.sh\n\n' "$1" "$MANIFEST_VERSION"; }

{ head version
cat <<YAML
PackageIdentifier: $ID
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: $MANIFEST_VERSION
YAML
} > "$out/$ID.yaml"

{ head installer
cat <<YAML
PackageIdentifier: $ID
PackageVersion: $version
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
ProductCode: SVRZ RC
ReleaseDate: $date
AppsAndFeaturesEntries:
- DisplayName: SVRZ RC
  Publisher: Luca Canepa
  DisplayVersion: $version
  ProductCode: SVRZ RC
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\SVRZ RC'
Installers:
- Architecture: x64
  InstallerUrl: $url
  InstallerSha256: $sha
ManifestType: installer
ManifestVersion: $MANIFEST_VERSION
YAML
} > "$out/$ID.installer.yaml"

{ head defaultLocale
cat <<YAML
PackageIdentifier: $ID
PackageVersion: $version
PackageLocale: en-US
Publisher: Luca Canepa
PublisherUrl: https://svrz-rc.openvolley.app
PublisherSupportUrl: https://github.com/$REPO/issues
Author: Luca Canepa
PackageName: SVRZ Referee Coaching
PackageUrl: https://svrz-rc.openvolley.app
License: MIT
LicenseUrl: https://github.com/$REPO/blob/main/LICENSE
ShortDescription: Referee coaching app of Swiss Volley Region Zürich
Description: 'The app of the referee coaches of Swiss Volley Region Zürich: take games to observe, fill in the observation form at the hall, sign it and send the report, with or without network. Signing in needs an account from the SVRZ referee commission.'
Moniker: svrz-rc
Tags:
- volleyball
- referee
- coaching
- svrz
ReleaseNotesUrl: https://github.com/$REPO/releases/tag/$tag
ManifestType: defaultLocale
ManifestVersion: $MANIFEST_VERSION
YAML
} > "$out/$ID.locale.en-US.yaml"

{ head locale
cat <<YAML
PackageIdentifier: $ID
PackageVersion: $version
PackageLocale: de-CH
Publisher: Luca Canepa
PackageName: SVRZ Referee Coaching
ShortDescription: App der Referee Coaches von Swiss Volley Region Zürich
Description: 'Die App der Referee Coaches von Swiss Volley Region Zürich: Spiele zur Beobachtung übernehmen, das Beobachtungsformular in der Halle ausfüllen, unterschreiben und den Bericht senden, mit oder ohne Netz. Die Anmeldung braucht ein Konto der SVRZ-Schiedsrichterkommission.'
ManifestType: locale
ManifestVersion: $MANIFEST_VERSION
YAML
} > "$out/$ID.locale.de-CH.yaml"

echo "wrote $out ($url, sha256 $sha, $date)"
